### ISSUE TITLE
How to use it ubuntu-core?

### ISSUE THREAD

**Issue by vampywiz17** [dskad/qemu-ga-container#9]
Hello there,

i would use this container with my Proxmox server with ubuntu-core.

But i can not found the correct config to volumes.  I can not use shutdown and restart. Now i use this docker compose:

```
version: '3.3'
services:
    danskadra:
        container_name: qemu-ga
        volumes:
            - '/dev:/dev'
            - '/etc/os-release:/etc/os-release:ro'
            - '/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket'
            - '/sys/fs/cgroup:/sys/fs/cgroup'
            - '/sbin/shutdown:/sbin/shutdown'
            - '/bin/systemctl:/bin/systemctl'
            - '/usr/lib/systemd:/usr/lib/systemd'
            - '/lib64:lib64'
            - '/lib/x86_64-linux-gnu/:/lib/x86_64-linux-gnu/'
        devices:
            - '/dev/virtio-ports/org.qemu.guest_agent.0:/dev/virtio-ports/org.qemu.guest_agent.0'    
        privileged: true
        network_mode: host
        uts: host
        image: docker.io/danskadra/qemu-ga
```
here the ldd output:

```
ldd /bin/systemctl
        linux-vdso.so.1 (0x00007ffead5ee000)
        libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007f9d2cbb6000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f9d2cb8a000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f9d2cb5f000)
        liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f9d2cb3f000)
        libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f9d2ca70000)
        libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f9d2ca37000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f9d2c8f9000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9d2c6d1000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9d2ccd9000)
        libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f9d2c63a000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f9d2c614000)

```

**Comment by dskad** [comment]
The Dockerfile is missing the `-v` option for the guest agent, so it's not displaying any output. That makes it a little harder to debug. I'll be fixing that in a future release, so that it shows logging information by default. in the meantime that debug logging can be turned on by adding `-v` to the command like this to the docker-compose.yml.

```yaml
command: [ "-m", "virtio-serial", "-p", "/dev/virtio-ports/org.qemu.guest_agent.0", "-v" ]
```

When exec'ing into the qemu-ga container and running `systemctl --no-pager status`  I saw this error:

```
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

I missed an important mapping for systemctl to work on the host. The systemd runtime unit definitions
```yaml
- '/run/systemd/system:/run/systemd/system'
```

After adding that to your docker compose file, systemctl ran correctly.
```
# systemctl --no-pager status
● ubuntu
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Mon 2023-07-03 04:42:33 UTC; 1min 40s ago
   CGroup: /
           ├─docker 
           │ └─1d2be83e6c63bc2288fc92237e57ae93eea04d3e3403cf577e55cac3c07be0ae 
           │   ├─ 1 /usr/bin/qemu-ga -m virtio-serial -p /dev/virtio-ports/org.qemu.guest_agent.0 -v
           │   ├─ 8 sh
           │   └─14 systemctl --no-pager status
           ├─user.slice 
           │ └─user-1000.slice 
           │   ├─user@1000.service …
           │   │ └─init.scope 
           │   ├─session-3.scope 
           │   └─session-1.scope 
           ├─init.scope 
           └─system.slice 
             ├─systemd-networkd.service 
             ├─systemd-udevd.service 
             ├─snap.docker.compose.178994dd-c5c2-4a92-b390-b878d97df6f7.scope 
             ├─snap.docker.docker.de2e57fb-2887-48ba-8584-b63dffd07597.scope 
             ├─wpa_supplicant.service 
             ├─systemd-journald.service 
             ├─ssh.service 
             ├─system-serial\x2dconsole\x2dconf.slice 
             │ └─serial-console-conf@ttyS0.service 
             ├─snapd.service 
             ├─system-console\x2dconf.slice 
             │ └─console-conf@tty1.service 
             ├─systemd-resolved.service 
             ├─snap.docker.dockerd.service …
             ├─dbus.service 
             ├─systemd-timesyncd.service 
             └─systemd-logind.service 
```
I also noticed in Ubuntu Core, `/dev/virtio-ports/org.qemu.guest_agent.0` is a symlink to `/dev/vport1p1` so we could clean up the volume maps by getting rid of `- '/dev:/dev'` and updating the devices mapping. This is optional though.
```yaml
devices:
  - '/dev/vport1p1:/dev/virtio-ports/org.qemu.guest_agent.0'
```

So, adding the new systemd runtime mapping I came up with this and it is allowing me to shutdown and reboot through the agent, on Ubuntu Core 22.

```yaml
version: '3.3'
services:
  danskadra:
    container_name: qemu-ga
    volumes:
      - '/bin/systemctl:/bin/systemctl'
      - '/etc/os-release:/etc/os-release:ro'
      - '/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu'
      - '/lib64:/lib64'
      - '/run/systemd/system:/run/systemd/system'
      - '/sbin/shutdown:/sbin/shutdown'
      - '/sys/fs/cgroup:/sys/fs/cgroup'
      - '/usr/lib/systemd:/usr/lib/systemd'
      - '/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket'

    devices:
      - '/dev/vport1p1:/dev/virtio-ports/org.qemu.guest_agent.0'
    privileged: true
    network_mode: host
    uts: host
    image: docker.io/danskadra/qemu-ga
    command: [ "-m", "virtio-serial", "-p", "/dev/virtio-ports/org.qemu.guest_agent.0", "-v" ]
```

_NOTE: the last `command:` line is optional. It will just produce debug logging in the current qemu-ga container release._
